# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pm_app.proto for package 'pm_app'

require 'grpc'
require 'pm_app_pb'

module PmApp
  module PMApp
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pm_app.PMApp'

      rpc :GetData, AssetDetails, stream(DataPoint)
      rpc :SendData, DataPoint, Empty
    end

    Stub = Service.rpc_stub_class
  end
end
