# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pm_app.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("pm_app.proto", :syntax => :proto3) do
    add_message "pm_app.AssetDetails" do
      optional :id, :int32, 1
    end
    add_message "pm_app.DataPoint" do
      repeated :data, :string, 1
      optional :id, :int32, 2
    end
    add_message "pm_app.ResultDataPoint" do
    end
    add_message "pm_app.Success" do
      optional :success, :bool, 1
    end
    add_message "pm_app.Empty" do
    end
  end
end

module PmApp
  AssetDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pm_app.AssetDetails").msgclass
  DataPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pm_app.DataPoint").msgclass
  ResultDataPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pm_app.ResultDataPoint").msgclass
  Success = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pm_app.Success").msgclass
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pm_app.Empty").msgclass
end
